blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session
from exts import mail, db
from flask_mail import Message
from flask import request
import string
import random
from models import EmailCaptchaModel
from .forms import RegisterForm, LoginForm
from models import UserModel
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("auth", __name__, url_prefix="/auth")

@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print("User not found")
                return redirect(url_for("auth.register"))
            if check_password_hash(user.password, password):

                # cookie: 不适合存储太多数据，只适合存储少量数据；一般用来存放登录授权的东西
                # session: flask中的session是经过加密后存在cookie中的
                session["user_id"] = user.id
                return redirect("/")

            else:
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 表单验证：flask-wtf: wtforms
        form = RegisterForm(request.form)
        if form.validate():
            # 验证成功，将用户信息存储到数据库中
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login")) # 将视图函数转化成url
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))

# 把cookie中的session信息清掉
@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")



@bp.route("/captcha/email")
def get_email_captcha():
    email = request.args.get('email')

    # generate random verification code
    source = string.digits*4
    captcha = random.sample(source,4)

    s = ''.join(captcha)
    message = Message(subject="MemeLand Verification Code", recipients=[email], body=f"Your verification code is {s}")
    mail.send(message)

    # store verification code - use database
    email_captcha = EmailCaptchaModel(email=email, captcha=s)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({"code": 200, "message": "", "data": None})


@bp.route("/mail/test")
def mail_test():
    message = Message(subject="Test Message", recipients=["1716734606@qq.com"], body="testtest")
    mail.send(message)
    return "OK"

blueprints/qa.py
from flask import Blueprint, request, render_template, g, redirect, url_for
from .forms import PostForm, CommentForm
from models import PostModel, CommentModel
from exts import db
from decorators import login_required

bp = Blueprint("qa", __name__, url_prefix="/") #根路径做前缀

@bp.route("/")
def index():
    posts = PostModel.query.order_by(PostModel.create_time.desc()).all()
    return render_template("index.html", posts=posts)

@bp.route("/qa/publish", methods=["GET", "POST"])
@login_required
def publish_question():
    if request.method == "GET":
        return render_template("publish_question.html")
    else:
        form = PostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            post = PostModel(title=title, content=content, author=g.user)
            db.session.add(post)
            db.session.commit()
            return redirect("/")
        else:
            print(form.errors)
            return redirect(url_for("qa.publish_question"))

@bp.route("/qa/detail/<post_id>")
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    comments_count = len(post.comments)
    return render_template("detail.html", post=post, comments_count=comments_count)

@bp.route("/comment/publish", methods=["POST"])
@login_required
def publish_comment():
    form = CommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        comment = CommentModel(content=content, post_id=post_id, author=g.user)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("qa.post_detail", post_id=post_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.post_detail", post_id=request.form.get("post_id")))


@bp.route("/search")
def search():
    p = request.args.get("p")
    if not p:
        posts = PostModel.query.all()
    else:
        posts = PostModel.query.filter(PostModel.title.contains(p)).all()
    return render_template("index.html", posts=posts)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">MemeLand</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('qa.publish_question')}}">Post</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                            <input class="form-control mr-sm-2" type="search" placeholder="Keywords" aria-label="Search" name="p">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                        <span class="nav-link">{{  user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("auth.logout") }}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.login") }}">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("auth.register") }}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10" style="background-color: #fff; padding: 20px;">
            <h3 class="page-title">{{ post.title }}</h3>
            <p class="question-info">
                <span>Author: {{ post.author.username}}  </span>
                <span>Date: {{ post.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ post.content }}</p>
            <hr>
            <h4 class="comment-group-title">Comments ({{ comments_count }})</h4>
            <form action="{{ url_for('qa.publish_comment') }}" method="post">
                <div class="form-group">
                    <input type="text" placeholder="Type in Comments..." name="content" class="form-control">
                    <input type="hidden" name="post_id" value="{{ post.id }}">
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">Post Comment</button>
                </div>
            </form>
            <ul class="comment-group">
                {% for comment in post.comments %}
                <li>
                    <div class="user-info">
                        <img class="avatar" src="{{ url_for('static', filename='images/avatar.jpg') }}" alt="">
                        <span class="username">{{ comment.author.username }}</span>
                        <span class="create-time">{{ comment.create_time }}</span>
                    </div>
                    <p class="comment-content">{{ comment.content }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{%  block title %}
    MemeLand Forum - Home
{% endblock %}


{% block head %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}


{% block body %}
<div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <ul class="question-ul">
                    {% for post in posts %}
                    <li>
                        <div class="side-question">
                            <img class="side-question-avatar" src="../static/images/avatar.jpg" alt="">
                        </div>
                        <div class="question-main">
                            <div class="question-title"><a href="{{ url_for('qa.post_detail', post_id=post.id)}}">{{ post.title }}</a></div>
                            <div class="question-content">{{ post.content }}</div>
                            <div class="question-detail">
                                <span class="question-author">{{ post.author.username }}</span>
                                <span class="question-time">{{ post.create_time }}</span>
                            </div>
                        </div>
                    </li>
                    {%  endfor %}
                </ul>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{%  block title %}
    MemeLand Forum - Login
{% endblock %}


{% block head %}

{% endblock %}


{% block body %}
<div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Login Now</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}



templates/publish_question.html
{% extends "base.html" %}

{%  block title %}
    MemeLand Forum - Publish Post
{% endblock %}


{% block head %}
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10">
                <h1 style="text-align: center;">Write your Meme Thoughts</h1>
                <form action="#" method="post">
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="Enter title">
                    </div>
                    <div class="form-group">
                        <textarea name="content" class="form-control" rows="10" placeholder="Enter Content"></textarea>
                    </div>
                    <div class="form-group" style="text-align: right;">
                        <button class="btn btn-primary">Publish</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}






templates/register.html
{% extends "base.html" %}

{%  block title %}
    MemeLand Forum - Register
{% endblock %}


{% block head %}
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}


{% block body %}
    <div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">We will not share your email with others</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Verification Code</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="captcha">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="captcha-btn">Get Code</button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Username</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Confirm Password</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Register Now</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

